# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l9K_JE8pXGhDB5CqrfDXbkeCXP82Egen
"""

from math import pi
r = float(input ("Input the radius of the circle : "))
print ("The area of the circle with radius " + str(r) + " is: " + str(pi * r**2))

fn= input("Enter Filename: ")

f = fn.split(".")

print ("Extension of the file is : " + f[-1])