# -*- coding: utf-8 -*-
"""Mycap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17aULjQad-zEQX35Shd-mfr1JBj1HmwJe

Create a set in python
"""

myset = {"apple", "banana", "cherry"}
print(myset)

a=70
b=50
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)     #floor division
print(2**3)    #exponential 
print(a%b)   #modulus 
print(a^9)

x = 5

x *= 3

print(x)

x = 5

x%=3

print(x)

x = 5
y = 3

print(x == y)

x = 5
y = 3

print(x != y)

x = 5
y = 3

print(x > y)

x = 5
y = 3

print(x >= y)

PI = 3.14
r = float(input("Enter the radius of a circle:"))
area = PI * r * r
print("Area of a circle = %.2f" %area)

start, end = -4, 19
  
for num in range(start, end + 1):
      
    if num >= 0:
        print(num, end = " ")