# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J0AAtc08QqMgultDLNoN8moD-cZwzS6L
"""

#To print all positive number in range
list1 = [11, -21, 0, 45, 66, -93]
  
for num in list1:
    
    if num >= 0:
       print(num, end = " ")